import type { CadFeature, CadModelPreset } from "../types/cad";

export const INITIAL_CAD_FEATURES: CadFeature[] = [
  {
    id: "feat-1",
    name: "Base Sketch 1",
    type: "sketch",
    suppressed: false,
    visible: true,
    status: "ok",
    createdAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-20T10:00:00Z",
    author: "Alex Morgan",
    color: "#3b82f6",
    dimensions: [
      {
        id: "dim-1-1",
        name: "Width (X)",
        value: 120,
        unit: "mm",
        min: 10,
        max: 500,
        step: 1,
        description: "Primary base rectangle width",
      },
      {
        id: "dim-1-2",
        name: "Height (Y)",
        value: 80,
        unit: "mm",
        min: 10,
        max: 500,
        step: 1,
        description: "Primary base rectangle height",
      },
    ],
  },
  {
    id: "feat-2",
    name: "Base Extrude",
    type: "extrude",
    suppressed: false,
    visible: true,
    status: "ok",
    createdAt: "2025-02-20T10:05:00Z",
    updatedAt: "2025-02-20T10:05:00Z",
    author: "Alex Morgan",
    color: "#10b981",
    dimensions: [
      {
        id: "dim-2-1",
        name: "Depth (Z)",
        value: 25,
        unit: "mm",
        min: 1,
        max: 200,
        step: 1,
        description: "Extrusion distance along Z-axis",
      },
      {
        id: "dim-2-2",
        name: "Draft Angle",
        value: 0,
        unit: "deg",
        min: 0,
        max: 45,
        step: 0.5,
        description: "Taper angle along extrusion vector",
      },
    ],
  },
  {
    id: "feat-3",
    name: "Outer Corner Fillets",
    type: "fillet",
    suppressed: false,
    visible: true,
    status: "ok",
    createdAt: "2025-02-20T10:12:00Z",
    updatedAt: "2025-02-20T10:12:00Z",
    author: "Alex Morgan",
    color: "#f59e0b",
    dimensions: [
      {
        id: "dim-3-1",
        name: "Fillet Radius",
        value: 12,
        unit: "mm",
        min: 1,
        max: 40,
        step: 0.5,
        description: "Rounding radius for 4 outer corners",
      },
    ],
  },
  {
    id: "feat-4",
    name: "Center Bore Hole",
    type: "hole",
    suppressed: false,
    visible: true,
    status: "ok",
    createdAt: "2025-02-20T10:20:00Z",
    updatedAt: "2025-02-20T10:20:00Z",
    author: "Elena Rostova",
    color: "#ef4444",
    dimensions: [
      {
        id: "dim-4-1",
        name: "Hole Diameter",
        value: 36,
        unit: "mm",
        min: 2,
        max: 70,
        step: 1,
        description: "Main central pass-through bore diameter",
      },
      {
        id: "dim-4-2",
        name: "Countersink Angle",
        value: 90,
        unit: "deg",
        min: 60,
        max: 120,
        step: 5,
        description: "Bevel angle for screw flush seating",
      },
    ],
  },
  {
    id: "feat-5",
    name: "Top Face Chamfer",
    type: "chamfer",
    suppressed: false,
    visible: true,
    status: "ok",
    createdAt: "2025-02-20T10:30:00Z",
    updatedAt: "2025-02-20T10:30:00Z",
    author: "Elena Rostova",
    color: "#8b5cf6",
    dimensions: [
      {
        id: "dim-5-1",
        name: "Chamfer Distance",
        value: 2,
        unit: "mm",
        min: 0.5,
        max: 10,
        step: 0.5,
        description: "Bevel distance on top perimeter edges",
      },
    ],
  },
  {
    id: "feat-6",
    name: "Mounting Pocket Cutout",
    type: "cut_extrude",
    suppressed: false,
    visible: true,
    status: "ok",
    createdAt: "2025-02-20T10:42:00Z",
    updatedAt: "2025-02-20T10:42:00Z",
    author: "David Chen",
    color: "#ec4899",
    dimensions: [
      {
        id: "dim-6-1",
        name: "Pocket Width",
        value: 60,
        unit: "mm",
        min: 10,
        max: 100,
        step: 1,
        description: "Pocket horizontal clearance size",
      },
      {
        id: "dim-6-2",
        name: "Pocket Depth",
        value: 10,
        unit: "mm",
        min: 1,
        max: 24,
        step: 0.5,
        description: "Pocket blind cut depth into main body",
      },
    ],
  },
];

export const CAD_MODEL_PRESETS: CadModelPreset[] = [
  {
    id: "mounting-bracket",
    name: "Mounting Bracket Base",
    description: "Standard industrial mounting plate with corner fillets, center bore, and pocket cutout.",
    features: INITIAL_CAD_FEATURES,
  },
  {
    id: "shaft-collar",
    name: "Clamping Shaft Collar",
    description: "Cylindrical shaft locking collar with central bore and clamping slot.",
    features: [
      {
        id: "sc-1",
        name: "Cylinder Sketch",
        type: "sketch",
        suppressed: false,
        visible: true,
        status: "ok",
        createdAt: "2025-02-21T08:00:00Z",
        updatedAt: "2025-02-21T08:00:00Z",
        author: "Alex Morgan",
        color: "#3b82f6",
        dimensions: [
          {
            id: "sc-dim-1",
            name: "Outer Diameter",
            value: 90,
            unit: "mm",
            min: 20,
            max: 300,
            step: 1,
          },
        ],
      },
      {
        id: "sc-2",
        name: "Collar Extrude",
        type: "extrude",
        suppressed: false,
        visible: true,
        status: "ok",
        createdAt: "2025-02-21T08:05:00Z",
        updatedAt: "2025-02-21T08:05:00Z",
        author: "Alex Morgan",
        color: "#10b981",
        dimensions: [
          {
            id: "sc-dim-2",
            name: "Collar Thickness",
            value: 30,
            unit: "mm",
            min: 5,
            max: 100,
            step: 1,
          },
        ],
      },
      {
        id: "sc-3",
        name: "Shaft Bore",
        type: "hole",
        suppressed: false,
        visible: true,
        status: "ok",
        createdAt: "2025-02-21T08:10:00Z",
        updatedAt: "2025-02-21T08:10:00Z",
        author: "Elena Rostova",
        color: "#ef4444",
        dimensions: [
          {
            id: "sc-dim-3",
            name: "Shaft Diameter",
            value: 40,
            unit: "mm",
            min: 10,
            max: 80,
            step: 0.5,
          },
        ],
      },
      {
        id: "sc-4",
        name: "Edge Fillet",
        type: "fillet",
        suppressed: false,
        visible: true,
        status: "ok",
        createdAt: "2025-02-21T08:15:00Z",
        updatedAt: "2025-02-21T08:15:00Z",
        author: "Elena Rostova",
        color: "#f59e0b",
        dimensions: [
          {
            id: "sc-dim-4",
            name: "Radius",
            value: 3,
            unit: "mm",
            min: 0.5,
            max: 10,
            step: 0.5,
          },
        ],
      },
    ],
  },
  {
    id: "enclosure-box",
    name: "Sensor Enclosure Box",
    description: "Hollow sensor housing enclosure with thin shell walls.",
    features: [
      {
        id: "eb-1",
        name: "Box Sketch",
        type: "sketch",
        suppressed: false,
        visible: true,
        status: "ok",
        createdAt: "2025-02-21T09:00:00Z",
        updatedAt: "2025-02-21T09:00:00Z",
        author: "David Chen",
        color: "#3b82f6",
        dimensions: [
          {
            id: "eb-dim-1",
            name: "Length",
            value: 150,
            unit: "mm",
            min: 50,
            max: 400,
            step: 1,
          },
          {
            id: "eb-dim-2",
            name: "Width",
            value: 100,
            unit: "mm",
            min: 30,
            max: 300,
            step: 1,
          },
        ],
      },
      {
        id: "eb-2",
        name: "Solid Extrude",
        type: "extrude",
        suppressed: false,
        visible: true,
        status: "ok",
        createdAt: "2025-02-21T09:05:00Z",
        updatedAt: "2025-02-21T09:05:00Z",
        author: "David Chen",
        color: "#10b981",
        dimensions: [
          {
            id: "eb-dim-3",
            name: "Height",
            value: 50,
            unit: "mm",
            min: 10,
            max: 200,
            step: 1,
          },
        ],
      },
      {
        id: "eb-3",
        name: "Hollow Shell",
        type: "shell",
        suppressed: false,
        visible: true,
        status: "ok",
        createdAt: "2025-02-21T09:12:00Z",
        updatedAt: "2025-02-21T09:12:00Z",
        author: "David Chen",
        color: "#06b6d4",
        dimensions: [
          {
            id: "eb-dim-4",
            name: "Wall Thickness",
            value: 2.5,
            unit: "mm",
            min: 0.8,
            max: 10,
            step: 0.1,
          },
        ],
      },
    ],
  },
];
