import type { Agent, SystemGauges, TelemetryEvent, RealmState } from "../types/telemetry";

export const initialAgents: Agent[] = [
  {
    id: "agent-01",
    name: "Aether-01",
    role: "Quantum Core Coordinator",
    status: "active",
    currentTask: "Synthesizing vector embeddings",
    cpuUsage: 42,
    memoryUsage: 68,
    latencyMs: 14,
    uptime: "99.98%",
    lastHeartbeat: new Date().toISOString(),
  },
  {
    id: "agent-02",
    name: "Nexus-09",
    role: "Telemetry Ingestion Pipeline",
    status: "active",
    currentTask: "Streaming signal events",
    cpuUsage: 61,
    memoryUsage: 54,
    latencyMs: 8,
    uptime: "99.99%",
    lastHeartbeat: new Date().toISOString(),
  },
  {
    id: "agent-03",
    name: "Vortex-X",
    role: "Anomaly Detector",
    status: "syncing",
    currentTask: "Recalibrating quantum noise filter",
    cpuUsage: 89,
    memoryUsage: 82,
    latencyMs: 65,
    uptime: "98.50%",
    lastHeartbeat: new Date().toISOString(),
  },
  {
    id: "agent-04",
    name: "Chronos-04",
    role: "State Reconciler",
    status: "warning",
    currentTask: "Resolving dimensional drift",
    cpuUsage: 78,
    memoryUsage: 91,
    latencyMs: 142,
    uptime: "96.40%",
    lastHeartbeat: new Date().toISOString(),
  },
  {
    id: "agent-05",
    name: "Helios-V",
    role: "Security Sentinel",
    status: "idle",
    currentTask: "Awaiting authentication matrix scan",
    cpuUsage: 12,
    memoryUsage: 30,
    latencyMs: 22,
    uptime: "99.95%",
    lastHeartbeat: new Date().toISOString(),
  },
];

export const initialSystemGauges: SystemGauges = {
  cpuUsage: 56.4,
  cpuTemp: 58.2,
  cpuCores: [42, 68, 55, 71, 38, 82, 49, 46],
  memoryUsedGb: 24.8,
  memoryTotalGb: 32.0,
  memoryUsage: 77.5,
  swapUsedGb: 1.2,
  networkInKbps: 1420,
  networkOutKbps: 3890,
};

export const initialTelemetryEvents: TelemetryEvent[] = [
  {
    id: "evt-1001",
    timestamp: new Date(Date.now() - 1000 * 12).toISOString(),
    severity: "info",
    source: "Aether-01",
    message: "Vector index recalculation completed in 142ms",
    details: "Cluster shard 04 optimized. 1,420,000 vectors indexed.",
  },
  {
    id: "evt-1002",
    timestamp: new Date(Date.now() - 1000 * 35).toISOString(),
    severity: "warning",
    source: "Chronos-04",
    message: "High memory pressure threshold exceeded (>90%)",
    details: "Cache flush recommended for heap segment 0x7FFF.",
  },
  {
    id: "evt-1003",
    timestamp: new Date(Date.now() - 1000 * 78).toISOString(),
    severity: "success",
    source: "Supabase-Live",
    message: "Realtime channel 'signals-changes' subscribed",
    details: "Postgres change listener attached for public.signals.",
  },
  {
    id: "evt-1004",
    timestamp: new Date(Date.now() - 1000 * 120).toISOString(),
    severity: "info",
    source: "Nexus-09",
    message: "Ingested 50,000 telemetry packets / second",
    details: "Zero packet drop rate detected across edge nodes.",
  },
  {
    id: "evt-1005",
    timestamp: new Date(Date.now() - 1000 * 210).toISOString(),
    severity: "critical",
    source: "Vortex-X",
    message: "Quantum phase displacement spike (+3.2% jitter)",
    details: "Dimensional alignment compensation initiated automatically.",
  },
];

export const initialRealms: RealmState[] = [
  {
    id: "realm-01",
    name: "Primordial Origin Alpha",
    code: "REALM-PRIME",
    status: "synchronized",
    activeNodesCount: 12,
    totalNodesCount: 12,
    quantumSyncRate: 99.4,
    anomalyLevel: 1.2,
    dimensionalPhase: "0xFE4A - Harmonic",
    activeDirectives: [
      "Autonomic Load Balancing",
      "Realtime Supabase Sync",
      "Quantum Entropy Stabilization",
    ],
    nodes: [
      { id: "node-a1", name: "Core Cluster - US East", region: "us-east-1", latencyMs: 12, status: "online", load: 45 },
      { id: "node-a2", name: "Edge Relay - EU Central", region: "eu-central-1", latencyMs: 28, status: "online", load: 62 },
      { id: "node-a3", name: "Quantum Mirror - AP South", region: "ap-south-1", latencyMs: 74, status: "online", load: 38 },
      { id: "node-a4", name: "Fallback Vault - US West", region: "us-west-2", latencyMs: 35, status: "online", load: 19 },
    ],
  },
  {
    id: "realm-02",
    name: "Dimensional Node Beta",
    code: "REALM-BETA",
    status: "fluctuating",
    activeNodesCount: 7,
    totalNodesCount: 8,
    quantumSyncRate: 88.7,
    anomalyLevel: 14.8,
    dimensionalPhase: "0x89BC - Phase Shift",
    activeDirectives: [
      "Temporal Drift Mitigation",
      "Heuristic Subspace Scan",
    ],
    nodes: [
      { id: "node-b1", name: "Hypervisor Node 01", region: "sa-east-1", latencyMs: 110, status: "online", load: 88 },
      { id: "node-b2", name: "Hypervisor Node 02", region: "ap-northeast-1", latencyMs: 145, status: "degraded", load: 94 },
      { id: "node-b3", name: "Time Sync Gateway", region: "eu-west-1", latencyMs: 210, status: "offline", load: 0 },
    ],
  },
];
